m-lab/ndt-server

ndt-server.go, ndt-server_test.go, testdata/unittest_client.js
During canary deployment at tyo02, we found that there were goroutines blocked indefinitely in `manageC2sTest` (called from the control channel) waiting for a client test to run that never came.
This change improves the use of context in the control channel and TestResponder goroutines to ensure that all goroutines eventually exit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/13)
=> Improve use of contexts to ensure goroutine shutdown

ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/14)
=> Use fewer log-spaced bins on rates. Use fewer test duration buckets

cmd/ndt-cloud-client/main.go, ndt7/client.go
Attempt to remove any remaining optional complexity. Slightly
tweak the code such that we print the current speed on the
standard output, which helps to estimate whether we're doing
a good job when downloading from the local host.
Closes #18.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/19)
=> Finish simplifying ndt7 client

bbr/bbr.go, bbr/bbr_linux.c, bbr/bbr_linux.go, bbr/bbr_linux.h, bbr/bbr_stub.go, html/libndt7.js, html/ndt7-worker.js, html/ndt7.html, ndt-server.go, ndt7/client.go, ndt7/server.go, ndt7/spec.go, spec/ndt7-protocol.md
I've run some more tests in 2G/3G/4G networks. This led me to the following improvements:
1. using a worker for the web client, so the UI is not locked
2. modify the protocol to allow for sending measurement messages with padding, so that the client receives more measurements regardless of the delay caused by 2G/3G/4G buffers
3. other, smaller, miscellaneous, useful fixes
I have also experimented with `TCP_NOTSENT_LOWAT` but that diff is not ready to be included in this PR yet, and I feel like the code in here has been delayed for too much time already. I'll probably ask about this option to @mattmathis later today or in the next days.
--- …
=> Improvements after testing on 2G/3G/4G networks

spec/ndt7-protocol.md
<strike>This is a set of [stacked diffs](https://jg.gg/2018/09/29/stacked-diffs-versus-pull-requests/). Some of them are easy fixes, some of them propose changes in the spec. What I'd like the reviewer to do is the following: (1) review the easy fixes and authorise me to merge them, if they're okay; (2) discuss about the more complex changes (i.e. using a vector of objects for measurements).</strike>
(it turns out that I didn't fully understand stacked diffs.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/57)
=> ndt7 spec clarifications: half duplex and minor details

.travis.yml
This has been written as part of #62, which is currently WIP. When trying to fix a broken build, I noticed that our current build will build files not only inside docker but also outside docker, i.e. in travis.
This happens because we're using as build language `go`. However, the current testing system is such that we want to do everything inside containers. Hence, disable building stuff outside.
(In #62 I am removing C code and using Go directly to get BBR stats. The build fails in travis because of missing header definitions, and succeeds in containers because such definitons are present.)
Asking a review to @pboothe because he most recently worked on the travis build.
--- …
=> travis: disable automatic go build, only use docker

.travis.yml, TestDockerfile, legacy/c2s/c2s.go, legacy/legacy.go, legacy/metrics/metrics.go, legacy/protocol/protocol.go, legacy/protocol/protocol_test.go, legacy/s2c/s2c.go, legacy/testresponder/testresponder.go, legacy/testrunner.go, metrics/metrics.go, ndt-server.go, ndt-server_test.go, test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/52)
=> The server now speaks non-ws NDT with JSON messages.

bbr/bbr_linux.go, ndt7/client.go, ndt7/model/appinfo.go, ndt7/model/bbrinfo.go, spec/ndt7-protocol.md
It makes sense to use float64 where the measurement unit is
a floating, but using it when we're sending integer quantities
is actually a bit surprising.
While it's true that `float64` is native to the i386 platform
and `int64` it's not, I don't even know whether `int64` is slower
than `float64` and, even if that was the case, it would probably
be weird anyway to use `float64` rather than `int64`.
Another reason why I was using `float64` is that I didn't know
how to extact `int64`s from C code. But C code is gone in the
previous commit. Conclusion: let's use `int64` instead.
Now, why `int64` and not `uint64`? The different is subtle. We
know that in many cases golang is using signed integers also
for sizes, so that is not so surprising in golang. In Java there
is no unsigned, so in theory …
=> spec: use int64, allow counter-flow messages

ndt-server.go
Cherry pick of 27a942d58c5948aea053782720ba48108bb289fd
with the required changes to make it apply cleanly.
With this diff applied, ndt7 works again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/76)
=> fix(ndt-server.go): make ndt7 work again

legacy/c2s/c2s.go, legacy/s2c/s2c.go
`Cancel` is an ephemeral member of the `TestResponder` struct.  `Close` is a permanent method that may or may not call `Cancel`.  Only `Close` should call `Cancel`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/85)
=> Cancel -> Close

ndt7/download/download.go, ndt7/saver/saver.go
As explained in the documentation of the new package, `saver`, we're
factoring out this common piece of code because we really know it's
gonna be needed by both the download and the upload.
My goal with all this yak shaving is to parachute us safely from
a state where the download works to a state in which both the
download and the upload work and they look like correct.
More changes to come.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/97)
=> Factor out common code for saving results

ndt-server.go, ndt7/download/download.go, ndt7/handler/handler.go, ndt7/results/file.go, ndt7/spec/spec.go
This commit completes the yak shaving required to restructure
the code such that adding support for upload is easy.
We create a new ndt7/handler package where we do most of the
common work required by both download and upload.
This common code has been moved out of downlad, which now
looks very simple and understandable (IMHO).
27b2504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/98)
=>  ndt7: refactor code to make adding upload easy

ndt-server.go
Closes #103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/104)
=> ndt-server.go: use prometheusx.MustServeMetrics()

ndt-server.go, ndt7/handler/handler.go
Discovered when trying to write a JavaScript client
that is not served directly by m-lab/ndt-server.
While there, make sure we print a meaningful error
message when the UPGRADE fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/105)
=> ndt7: enable CORS

legacy/legacy.go, legacy/meta/meta.go, legacy/meta/meta_test.go, legacy/protocol/protocol.go
This change adds support to the META test for all client types.
The NDT meta protocol does not specify a limit on the number of values a client may send to the server. This PR sets the limit to 10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/121)
=> Add META test to ndt-server

ndt7/download/download.go, ndt7/download/measurer/measurer.go, ndt7/model/connectioninfo.go, ndt7/model/measurement.go, ndt7/results/file.go, ndt7/saver/saver.go, spec/data-format.md, spec/ndt7-protocol.md
Addresses #123 and #124 for ndt7. Unclear if further action is required for the legacy protocol at this stage. If not, we should probably close the relevant issues when this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/126)
=> Provide clients with the four tuple and the UUID

legacy/legacy.go, legacy/meta/meta.go, legacy/metrics/metrics.go, ndt-server_test.go
The current legacy implementation does not include active sfw and mid tests. When a client requests specific test types, the server may optionally return only the supported tests that the client ought to respect.
This change adds monitoring to observe how often we have clients requesting the sfw and mid tests. 
As well, this change removes options from the PLAIN,TLV and PLAIN,JSON test clients where unnecessary and where necessary document the reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/128)
=> Add new monitoring for requested tests and submitted meta values

test.sh
etl now depends on ndt-server.  This adds go vet on the etl repo to ensure we don't break it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/146)
=> add go vet etl to check etl dependencies

ndt5/singleserving/server.go
Previously, the PlainServer could return an invalid protocol.MeasuredConnection when the context timed out, for instance, as a result of a client that never connected to an S2C or C2S test server.
The invalid MeasuredConnection instance caused panics that resulted in the server SIGSEGV https://github.com/m-lab/ndt-server/issues/153
This change detects and returns an error when the `conn == nil`.
Closes #153 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/154)
=> Check for nil connection after timeout

ndt5/ndt5.go, ndt5/plain/plain.go, ndt5/protocol/protocol.go, ndt5/s2c/s2c.go, ndt5/singleserving/server.go, ndt5/web100/web100_linux.go
Addresses https://github.com/m-lab/ndt-server/issues/160
As part of the fdcache, the server maintains two fds for the same client test connections. Both must be closed for the client to see the connection terminated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/162)
=> Explicitly close the download test connection after 10sec

ndt5/web100/web100_linux.go
This is a change that I failed to save so didn't get committed in https://github.com/m-lab/ndt-server/pull/162
Without this change, the server should still behave correctly but will attempt to close the fd twice, which should fail harmlessly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/165)
=> Complete removal of close in MeasureViaPolling

ndt5/ndt5.go
SplitN was finding at most N fields in the given message, which with a value of 1 always meant "words" == "msg" which always failed to be found in the okayWords map.
With SplitN(2) panicMsgToErrType can correctly extract the first word.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/167)
=> Split error message to extract first word

TestDockerfile, ndt-server_test.go
This change adds measurement-kit client to the integration test suite. Previously, it was the only client that reported an error from https://github.com/m-lab/ndt-server/issues/160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/168)
=> Add measurement-kit to the integration tests

metadata/namevalue.go, ndt5/control/data.go, ndt5/meta/meta.go, ndt5/meta/meta_test.go, ndt7/model/archivaldata.go, ndt7/results/file.go, ndt7/results/metadata.go
This change eliminates `map[string]string` types from the NDTResult and subfields. As a result, we should be able to use the native NDTResult struct with `bigquery.InferSchema` method. This will greatly simplify the ETL parser code for NDT data.
Part of https://github.com/m-lab/dev-tracker/issues/402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/176)
=> Convert ClientMetadata map types to []metadata.NameValue

ndt5/protocol/messager.go, ndt5/protocol/messager_test.go, ndt5/s2c/s2c.go, ndt5/web100/web100.go, ndt5/web100/web100_linux.go, ndt7/measurer/measurer.go, ndt7/model/tcpinfo.go, tcpinfox/tcpinfox.go, tcpinfox/tcpinfox_linux.go, tcpinfox/tcpinfox_stub.go
Lays the groundwork for eliminating quantization by using the existing measurement system to track bytes received.
Lays the groundwork for future simulation of legacy data entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/177)
=> Adds tcpinfo to web100 export data.

spec/data-format.md, spec/ndt7-protocol.md
This modification of the ndt7 spec is non backward compatible
therefore I have bumped the version accordingly.
When reading the spec after this changes have been applied, I am now
confident that we can make a first public release soon.
The following list describes what changed:
1. bumped the version number
2. added a non-normative section describing the design choices of
ndt7 as recently discussed with @pboothe and @mattmathis
3. reorganized the protocol description to group handshake-related
information and websocket related information
4. [API CHANGE] now the client MUST include an user-agent
during the websocket handshake
5. [API CHANGE] removed ambiguity on how the server SHOULD process
query string keys without a value: now the server SHOULD consider
them like keys with an empty …
=> spec/ndt7: address several outstanding issues

ndt5/plain/plain.go, ndt5/plain/plain_test.go
* Add a timeout to prevent slow-clients causing goroutine leaks
* Always close the connection when returning from `sniffThenHandle`
Fixes https://github.com/m-lab/ndt-server/issues/117
Part of https://github.com/m-lab/dev-tracker/issues/412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/184)
=> Add a timeout to prevent slow-clients causing goroutine leaks

ndt5/metrics/metrics.go, ndt5/plain/plain.go, ndt5/protocol/messager.go, ndt5/s2c/s2c.go, ndt5/web100/web100_linux.go
Add the UUID to the output.
Improve logging and fix some log spam.
Add fields to web100.
Part of #185, #161, #159, https://github.com/m-lab/dev-tracker/issues/412, https://github.com/m-lab/dev-tracker/issues/329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/186)
=> Small fixes, removing blockers.

fullstack/Dockerfile, fullstack/README.md, fullstack/start.sh
This will allow others to run everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/187)
=> Add full stack dockerfile

ndt7/download/sender/sender.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/204)
=> ndt7/d/s/sender.go: remove unused variable

fullstack/start.sh
This is an untested draft PR attempting to fix #211 @pboothe PTAL?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/212)
=> attempted fix for #211

fullstack/start.sh
After some thought last night, I realized we moved the codebase in the wrong direction.  Instead, the UUID prefix should be in a file in `/tmp` and be recreated on every run.  Keeping the old file around puts the uniqueness of the UUIDs at risk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/213)
=> UUIDs are now in tmpfiles

ndt5/web100/web100_linux.go
This PR adds a `defer fp.Close()` in the `measureUntilContextCancellation` func so that the connection gets closed when the context is cancelled. At some point in the past that `Close()` was removed (https://github.com/m-lab/ndt-server/pull/179), it's unclear to me why.
This should fix the timeout some clients are intermittently experiencing at the end of a S2C test. While some clients are robust enough to ignore the timeout, others are currently failing.
Hopefully fixes https://github.com/ooni/probe/issues/877 once released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/218)
=> Fix timeout at the end of S2C tests

TestDockerfile
Builds take too long. Now they will take less time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/230)
=> Speed up builds using parallel make

data/result.go, html/ndt7-ping.js, html/ndt7.html, ndt-server.go, ndt7/download/download.go, ndt7/download/sender/sender.go, ndt7/handler/handler.go, ndt7/measurer/measurer.go, ndt7/model/appinfo.go, ndt7/model/measurement.go, ndt7/model/wsinfo.go, ndt7/ping/ping.go, ndt7/receiver/receiver.go, ndt7/results/file.go, ndt7/spec/spec.go, ndt7/upload/sender/sender.go, ndt7/upload/upload.go
That's WIP for #192 
I have a few questions I'm unsure about:
- is it okay to carry `start` around the way it's implemented? It looks a bit messy to me, but I'm quite okay with that.
- does it make sense to send `WSInfo` messages to client in `/upload` and `/download`? I feel like those may be eventually useful, those datapoints feed my curiosity about queuing, but I have no immediate use for the data.
- should `WSInfo` be a separate optional sub-message in the spec or should it extend `AppInfo` with optional fields?
- there is a feedback loop between the goroutines: `sender` (sends ping to) → `[conn]` (eventually delivers pong to) → `receiver` (sends RTT estimate back to client) → `sender`. The current implementation uses buffered channel for RTT estimates to avoid blocking on `pongch <- …
=> Saving websocket RTT samples

test.sh
Now that ETL is using modules, this bidirectional "code health" check has strictly negative value for NDT-server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/253)
=> Remove connection to ETL pipeline.

ndt7/download/download.go, ndt7/measurer/measurer.go, ndt7/upload/upload.go
As documented in #238, we would like to reduce the pipeline
structure and the dependency on channels. We have a reasonably
clear idea of what we want to do.
Let us do this piecemeal.
In this first diff, I'm changing the measurer to be a
struct rather than just a func. By doing that, I'm
creating the opportunity for storing the measurements
collected by the measurer into the measurer itself rather
than publishing them downstream to a channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/248)
=> ndt7: start refactoring to reduce the number of channels

access/tx.go, access/tx_test.go, ndt-server.go
This change adds the access controller to ndt7 clear text handler and generalizes the access controller setup to allow chaining multiple controllers in the future. This change also allows TxController to be disabled with a warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/259)
=> Add access control to ndt7:80 and ignore TxController errors

ndt7/measurer/measurer.go, spec/ndt7-protocol.md
We noticed how annoying is not doing that with @robertodauria during
the review of https://github.com/m-lab/ndt7-client-go/pull/39.
As part of such work, we also double checked that every TCPInfo
field described by the spec is a meaningful ndt7 summary.
As a result we can now close #194.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/261)
=> ndt7: always include ConnectionInfo

access/tx.go, access/tx_test.go, ndt-server.go, ndt5/plain/plain.go, ndt5/plain/plain_test.go
Two changes:
1. Check device TX usage every 100ms instead of 1sec, with a slow decay. 
2. Apply TxController to ndt5 plain socket Accept calls.
The combination of these changes will apply the tx limit to all control connections and add some hysteresis to interface usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/268)
=> Apply TxController to ndt5 "plain" socket Accept calls

access/control.go, access/control_test.go, access/token.go, access/token_test.go
This change adds access.TokenController which is capable of admitting or rejecting clients based on an "access_token" HTTP parameter. This change explicitly allows monitoring to issue access_tokens, and assign a context value to the HTTP request context, so that subsequent access controllers can a) identify monitoring requests, b) allow the test even if it would ordinarily be rejected.
To provide the option of exempting monitoring clients, the TokenController should be applied first in a sequence of access controllers.
This controller is not yet enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/269)
=> Add access.TokenController for monitoring-aware token-based access control

data/result.go, ndt5/ndt5.go, ndt7/handler/handler.go
This change separates the NDTResult struct into two NDT5 and NDT7 types.
This change does not remove any fields from the new NDT7 struct, in order to remain maximally backward compatible with existing ndt7 archived data.
From adhoc testing in sandbox by @gfr10598, we expect that the etl parse (once updated to use this new ndt5result struct) should be able to continue writing to the existing tables. However, some manual steps will be necessary to fix the existing table schemas before `etl/cmd/update-schema` works as intended for the ndt5 tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/271)
=> Add separate structs for ndt5 & ndt7 datatypes

metrics/metrics.go, ndt5/handler/wshandler.go, ndt5/ndt5.go, ndt5/plain/plain.go, ndt7/handler/handler.go
This change adds a new label for `monitoring=true` or `monitoring=false` to the `TestRates` `ndt_test_rate_mbp` histogram metric. This change also adds rate collection for ndt7 measurements.
This change relies on earlier changes to process access tokens and recognize requests as monitoring (vs regular client requests).
Until the locate v2 service supports a monitoring resource that allocates access tokens to use in the e2e monitoring, the e2e measurements will not be correctly identified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/276)
=> Add monitoring label to TestRate histogram

ndt-server.go, ndt5/ndt5.go, ndt7/handler/handler.go
This change fixes https://github.com/m-lab/ndt-server/issues/278
This change adds support for distinguishing ndt5 and ndt7 protocols in the TestRates prometheus metric.
This change will break historical continuity for the ndt5 protocol labels. The following translations will appear in the metrics upon deployment.
* WS -> ndt5+ws
* WSS -> ndt5+wss
* PLAIN -> ndt5+plain
This change adds distinct protocol values for secure and insecure ndt7 connections:
* ndt7+ws
* ndt7+wss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/279)
=> Label ndt5 and ndt7 test rates based on ws or wss protocol

html/ndt-browser-client.js
This PR attempts to resolve issue #281.
Test was done here:
https://ndt-iupui-mlab1-lga0t.mlab-sandbox.measurement-lab.org/static/widget.html
This was tested by logging into the ndt-server container on that node (mlab1-lga0t) and manually modifying `html/ndt-browser-client.js` in the running instance. Previously this bug would manifest within 4 or 5 runs. With this modification I was unable to trigger the bug in 10 or 15 runs.
The bug is identifiable by clicking on the "Advanced" tab and finding a floating point value for `c2sRate`, which should always be an integer (the server only sends an integer).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/283)
=> Attempts to fix a small race condition in setting that.results.c2sRate.

ndt-server.go
This change adds independent flags for requiring access tokens for the ndt5 and ndt7 servers.
This change will allow us to require access tokens on ndt7 before ndt5 in order to remediate some negative client scheduling behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/286)
=> Add separate token required flags for ndt5 and ndt7

ndt5/protocol/protocol.go, ndt5/s2c/s2c.go
While investigating a higher than expected error rate from the throttled ndt5-client used in the e2e monitoring with access tokens, I discovered that the cause of failure from the client perspective was the server handling `FillUntil` errors as fatal.
[FillUntil in prometheus metrics][prom] is the second most frequent error from clients. In the case of the ndt5-client, the error is a result of two steps:
* a slow client causes the ndt-server to stall in [`ws.WritePreparedMessage()` ][write].
* the client adds a timeout of [15sec to testconn][timeout], and the [downloader goroutine][downloader] runs until a read error or timeout.
After the 15sec timeout, the client closes the test connection. Because the server was blocked in a write, the write returns an error and returns from FillUntil. …
=> Make FillUntil errors non-fatal

ndt-server.go
This change is a backward compatible update to the `-token.verify-key` flag of the ndt-server. This change will now allow caller to provide multiple verify keys in order to allow key rotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/288)
=> Add support for loading multiple verify keys

ndt-server_test.go, ndt5/c2s/c2s.go, ndt5/c2s/c2s_test.go, ndt5/s2c/s2c.go
While working on the ndt5 parser migration to standard columns, I discovered that we are not collecting some metrics in the ndt5 archival structure.
This change adds two new values to the s2c and c2s archival data: LossRate and MinRTT respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/289)
=> Add metrics shared with clients to ArchivalData

metrics/metrics.go, ndt5/ndt5.go, ndt7/download/download.go, ndt7/download/sender/sender.go, ndt7/handler/handler.go, ndt7/metrics/README.md, ndt7/metrics/metrics.go, ndt7/receiver/receiver.go, ndt7/upload/sender/sender.go, ndt7/upload/upload.go, netx/net.go
This change adds metrics to instrument the ndt7 server in a similar way to the ndt5 server today. Specifically, this change adds four ndt7 specific metrics (see README for details).
* `ndt7_client_connections_total{direction, status}`
* `ndt7_client_test_results_total{protocol, direction, result}`
* `ndt7_client_sender_errors_total{protocol, direction, error}`
* `ndt7_client_receiver_errors_total{protocol, direction, error}`
This change also introduces a simple gauge to count the number of currently open netx.Conn file pointers. This will aid it detecting potential leaks, or simply reporting the current number of open connections to the server.
* `netx_current_open_conns`
--- …
=> Add metrics to ndt7 server and netx.Conns

ndt7/handler/handler.go, ndt7/spec/spec.go, netx/net.go
During load testing, I discovered that ndt5 can close netx.Conns multiple times. This change guarantees that the metric is only decremented once.
During load testing, I discovered that ndt7 RAM requirements limit maximum concurrent connections to 1/3 ndt5's level with ndt-server RSS maxing out around 9.5GB before the system failed. This appears to be due to the extremely large websocket buffers. This change adds a new constant for the websocket buffer sizes of 1MB. Buffer sizes are independent of websocket message sizes.
With these settings load testing was able to comfortably support 300 concurrent connections (the previous water mark from NDT5) or ~1700 tests/min (very close to the theoretical limit of 1800 / min for 10sec tests, which is much tighter run time than ndt5's 15sec/test). …
=> Fix netx.Conn metrics and reduce ndt7 websocket buffer

ndt7/download/sender/sender.go, ndt7/receiver/receiver.go, ndt7/upload/sender/sender.go
This change fixes the accidental omission of `.Inc()` on the sender and receiver error metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/301)
=> Fix error metric increments

ndt-server.go, ndt5/singleserving/server.go
This change fixes https://github.com/m-lab/ndt-server/issues/293 and adds similar preventative timeouts to the `ServeOnce` servers used by NDT5 plain, ws, and wss measurements.
This change adds `ReadTimeout` and `WriteTimeout` to the `http.Server` used by the control channel for all NDT5 and NDT7 servers. The plain server control channel [provides it's own timeout logic](https://github.com/m-lab/ndt-server/blob/master/ndt5/plain/plain.go#L152).
However, for `singleserving` servers, this change now adds a context timeout in the `plainServer.ServeOnce` logic and uses the same `http.Server` timeouts as the control ports for ws and wss servers.
Also fixes https://github.com/m-lab/ndt-server/issues/122
For a summary of how `http.Server` timeouts apply to the connection lifetime, see: …
=> Create http.Server with Read and Write timeouts

ndt5/c2s/c2s.go, ndt5/meta/meta.go, ndt5/ndt/server.go, ndt5/ndt5.go, ndt5/s2c/s2c.go
This change makes prometheus metric labels consistent between ndt5 and ndt7 metrics without changing archival data. This makes it much easier to interpret dashboards that combine metrics from both NDT5 and NDT7 because they will begin using the same label names.
This change updates the "protocol" label for all ndt5 metrics to use the same label string used by the "TestRate" histogram metric.
Specifically:
* "WSS"  becomes "ndt5+wss"
* "WS" becomes "ndt5+ws"
* "PLAIN" becomes "ndt5+plain"
Because the `ConnectionType` protocol is part of the NDT5 archived result, this change preserves the current `String()` format of the `ConnectionType`
--- …
=> Add consistent ndt5 protocol metric labels

ndt5/ndt5.go
This change adds the error message to the log message when the JSON encoder fails to encode a result.
This is an strange situation because the result struct does not have complex types, so it's unclear what is causing it to fail. Part of https://github.com/m-lab/ndt-server/issues/307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/308)
=> Update error log

docker-compose.yml
I am not super happy about exposing 80 and 443 because that would break
running docker-compose on a host that enforces privileged ports.
The fixes in this diff are such that I can run the instructions provided
in the README.md and access ndt7 endpoints.
Sadly, I have no way of testing this on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/318)
=> fix(docker-compose.yml): make sure it works on macOS

ndt-server.go
This change uses the function added in https://github.com/m-lab/access/pull/29 to allow access token metric labels to include the paths for ndt5 and ndt7 resources. This change will prevent random requests by bots from filling the `path=` label of the `controller_access_token_requests_total` metric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/324)
=> Allow path labels for ndt5 and ndt7 resources

ndt7/download/sender/sender.go, ndt7/spec/spec.go
The message scaling algorithm stopped at ~64k even if `MaxScaledMessageSize` is set to 1MB (`1 << 20`).
This one-line diff fixes the algorithm by comparing the current message size (rather than the total amount of bytes sent) to the maximum message size.
As a result, the first doubling happens after 16 messages and the subsequent ones every 8 messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/331)
=> ndt7: fix message scaling in the download measurement

ndt-server.go
Add -tls_config command line option to allow specifying either "intermediate" or "modern" TLS configuration based on recommendations at https://wiki.mozilla.org/Security/Server_Side_TLS, allowing for disabling of older TLS versions.
CurveP384 is not included in CurvePreferences as there is no optimized implementation in Go.
Default configuration is unchanged, so if no -tls_config parameter is specified existing behavior is maintained.
I recognize this is somewhat unnecessary, given that there's no real risk from using TLS 1.0 for speed tests, but this helps tick boxes in corporate security compliance checklists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/333)
=> Support cutomising TLS configuration

Dockerfile, Dockerfile.local, TestDockerfile
This PR pins the Go version used in the build container to 1.16 (the same version as the currently ongoing canary) and also the Alpine version for both containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/339)
Closes #338.
=> Update Dockerfile to pin Go and Alpine versions

ndt7/receiver/receiver.go
This change is very similar to https://github.com/m-lab/ndt7-client-go/pull/63 - instead of using `conn.ReadMessage()` which allocates memory for the message, we get an `io.Reader`, check the message type and don't process it further if the type is not `websocket.TextMessage`.
Even if this is usually not a problem on M-Lab production hardware, this patch allowed me to measure a 1 Gb/s link fully with a ODROID XU-4 (armv7, 32 bit) running ndt-server, reducing the CPU usage from ~250% to ~120%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/343)
=> Use a Reader in receiver.go to prevent unnecessary memory alloc

ndt5/ndt5.go
A portion of NDT5 tests panic, causing the `ServerMetadata` field not to be populated (~10%).
Example:
[Log](https://pantheon.corp.google.com/logs/query;query=%22ndt-4dkmn_1642699102_000000000029FF3C%22;timeRange=2022-02-28T15:00:00.000Z%2F2022-02-28T17:00:00.000Z;cursorTimestamp=2022-02-28T16:02:04.825169258Z?project=mlab-oti) from [panic](https://github.com/m-lab/ndt-server/blob/10d0acf0a86a3c82a00687e85e48c6cb506eb297/ndt5/ndt5.go#L223).
Resulting `ServerMetadata`.
This PR is moving the initialization of `ServerMetadata` so it happens before the panics.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/353)
=> Move NDT5 ServerMetadata to avoid panic

fullstack/Dockerfile, fullstack/start.sh
The script previously just verified that the socket file existed. The file is created by tcp-info ~immediately, but connecting to it returns a "connection refused" error for the first few milliseconds.
Instead of just checking for the socket's existence, we attempt to actually connect to it with socat before starting traceroute-caller and packet-headers.
Closes #215 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/355)
=> Fix race condition in fullstack start.sh

ndt7/handler/handler.go
Related to #361. I'll add some more information about the issue there.
This PR changes how `conn.Close()` is called at the end of a measurement. Even if the current code _looks_ correct, we have seen many instances where the receiver and sender goroutines are stuck reading from / writing to the socket for a very long time after the end of a measurement. The deferred Close() in handler.go is supposed to force-close the connection when the receiver returns, but since the receiver is stuck trying to read from the socket this deferred function actually never gets called. Instead of using a deferred function, we start a separate goroutine that waits on a context timeout (or manual cancellation, when everything goes well and the sender goroutine cancels the context).
Assuming this approach …
=> Force conn.Close() after MaxRuntime in handler.go

ndt7/measurer/measurer.go
One of the requirements identified in the To the Cloud milestone requires a means of determining whether the BBR module is loaded and available for NDT7 measurements.
This change adds a new prometheus counter metric to track the rate of successful bbr enabled events.
If a node was misconfigured (e.g. bbr module not loaded), then the failure rate would be > 0 while the success rate was == 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/363)
=> Add metric to count whether enabling BBR succeeded

ndt7/measurer/measurer.go
Counter metrics should have a suffix with `_total`. I accidentally forgot this when originally adding this counter in https://github.com/m-lab/ndt-server/pull/363. This change corrects the metric name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/366)
=> Name counter metric with correct _total suffix

ndt7/model/archivaldata.go
This PR removes the `bigquery:"-"` tag from the `ConnectionInfo` field.
Because this optional field was to be ignored by BQ, it caused a fatal error in the Gardener in an instance where it was included in the `json` file and BQ did not recognize the field.
```
20220806:ndt/ndt7 Load {Location: "gs://etl-mlab-oti/ndt/ndt7/2022/08/06/20220806T040510.251033Z-ndt7-mlab2-gru02-ndt.tgz.json"; Message: "Error while reading data, error message: JSON parsing error in row starting at position 951624: No such field: raw.Download.ClientMeasurements.ConnectionInfo. File: gs://etl-mlab-oti/ndt/ndt7/2022/08/06/20220806T040510.251033Z-ndt7-mlab2-gru02-ndt.tgz.json"; Reason: "invalid"}
``` …
=> Remove bigquery ignore tag for ConnectionInfo

bbr/bbr_linux.go, tcpinfox/tcpinfox_linux.go
`Fd()` removes the `O_NONBLOCK` flag from the descriptor before returning it.
From [os/file_unix.go](https://github.com/golang/go/blob/master/src/os/file_unix.go#L85):
```
// If we put the file descriptor into nonblocking mode,
// then set it to blocking mode before we return it,
// because historically we have always returned a descriptor
// opened in blocking mode. The File will continue to work,
// but any blocking operation will tie up a thread.
```
When `Fd()` is called on a `*os.File` obtained via `conn.File()`, this descriptor is actually a duplicate but the underlying socket is shared. The end result is that the original `conn` still thinks it has a non-blocking socket, while the socket actually became blocking. This causes things like `conn.Close()` blocking forever if no data is …
=> Replace calls to Fd() with syscall.RawConn.Control()

html/ndt7-upload.js
We've discovered, that while using the embedded js client to run ndt7 tests, the upload speeds are very low for the connections at higher speeds (we were testing it with 4G and 10G). The reason is that the WebSocket connection is closed at the begging of the tests. The connection is closed by the server because its buffer is overflowing. This happens on the following browsers: Chrome, Edge, and Safari. Firefox is completing the upload test normally for the same set-up.
As a fix for this issue, we're proposing lowering the maxMessageSize on the upload worker on the JS client from 16MB to 8MB. This is also a value used in the other JS client: [ndt7-js](https://github.com/m-lab/ndt7-js). This client could also replace the current one, if it's OK with you I could add it as a part of this PR. …
=> Lowering max message size in upload worker

ndt7/measurer/measurer.go
We have learned that in practice, we see many `status=false` due to "bad file descriptor" errors. Unfortunately, this is not the error case we were originally interested in for the `ndt7_measurer_bbr_enabled_total`. 
To be able to identify failures enabling BBR due to the module not being present, this change adds the error string to the metric labels. We are looking for the error `"no such file or directory"`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/373)
=> Add error string label to bbr enabled metric

logging/logging.go
The ndt-server generates debug level logging and this is operationally costly for log retention, collection and provides negligible benefit for production deployments.
Ultimately, this setting should be configurable. Until then, this change makes the default log level `InfoLevel`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/374)
=> Disable Debug level logging

Dockerfile.local
This change updates the Dockerfile.local to use go1.18.
This is part of https://github.com/m-lab/dev-tracker/issues/735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/375)
=> Update to golang 1.18

ndt-server.go, ndt-server_test.go
This PR adds a new `/health` endpoint for ndt-server, which writes out a 200 status code if the server is healthy (i.e., not in lame duck) and an error code otherwise.
This will be queried by the Heartbeat Service and incorporated into the local health assessment for the instance.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/376)
=> Add /health endpoint for ndt-server

html/ndt-browser-client.js
This PR changes the NDT5 client code to use the monotonic performance.now() instead of Date.now() where available. This fixes a rare bug that happens when the system clock is changed while a measurement is running, which would cause an incorrect client-side throughput to be displayed -- in extreme cases, even a negative value.
(The code [is basically the same](https://github.com/m-lab/ndt7-js/blob/main/src/ndt7-upload-worker.js#L7) as in ndt7-js)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/379)
=> Use performance.now() where available

spec/ndt7-protocol.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/381)
=> fix(ndt7-protocol): clarify ElapsedTime semantics

ndt-server.go, ndt7/handler/handler.go, ndt7/results/file.go
This change adds a new flag (preserving prior default behavior) to enable or disable compressing ndt7 result files.
After this change, the ndt-server can use `-compress-results=false` to disable gzip compressed result files, making them jostler/autoloader compatible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/383)
=> Add -compress-results flag to optionally disable compressing results

docker-compose.yml
This change updates the docker-compose.yaml to run the ndt-server with jostler in a local mode.
This configuration demonstrates:
* generation of ndt-server result schemas for ndt5 and ndt7 for use by jostler
* configuration of ndt-server to output results that are jostler/autoloader compatible (i.e. uncompressed json)
* configuration of jostler using local output mode, simulating upload to GCS bucket with a local directory.
Note: the jostler timeouts and size limits are for illustration purposes only, and not suitable for a production deployment.
This type of configuration could be used by a third-party running the ndt-server with the intent to share the data with M-Lab.
- - - …
=> Add example invocation with jostler

ndt-server.go
This change updates the default `-health_addr` to explicitly bind to localhost:8000 to prevent accidentally exposing this service to the public internet. This change should have not effect since the heartbeat service already [targets localhost unconditionally](https://github.com/m-lab/locate/blob/main/cmd/heartbeat/health/endpoint-check.go#L10)
Part of:
* https://github.com/m-lab/ops-tracker/issues/1798
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/391)
=> Bind the health check service to localhost

ndt-server.go, ndt-server_test.go, ndt7/handler/handler.go, ndt7/handler/handler_integration_test.go, ndt7/ndt7test/ndt7test.go
This change adds an `eventsocket.Server` to the ndt-server for the ndt7 protocol.
With this change, the ndt-server could operate as a replacement for tcp-info's eventsocket for deployments that run with standard sidecar services (e.g. uuid-annotator, or others) but without needing tcp-info to be the event source. In this configuration, the ndt-server itself becomes the event source, limiting events to verified ndt7 measurements (rather than every TCP connection).
For this change to be possible, the ndt7 `handler.Handler` methods now use a pointer receiver so that the `Handler.Events` field can be reset after `ndt7test.NewNDT7Server` creates a server using the default `eventsocket.NullServer`. As well, we add a `handler_integration_test.go` to allow import of the existing `ndt7test` …
=> Add optional eventsocket Server to ndt-server

ndt7/handler/handler_integration_test.go
The previous test implementation was flaky. This change uses a channel to signal that the `FlowDeleted` path has been reached.
While the `srv.Close()` will prevent new connections, and the `downloadHelper()` closes the client connection, there is still an independent handler goroutine that reaches the `FlowDeleted` path after a short delay. Rather than using a larger static delay, this change sets a maximum delay and waits for the `deleted` channel to close, allowing the test to stop as quickly as it's able to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/397)
=> Fix: deterministic check for FlowDeleted

html/ndt7.html
When using the default ndt7.html that's shipped here, you'll end up with non-functional wss (or https). This makes it protocol agnostic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/400)
=> avoid mixed content breaking when using https

go.mod, go.sum, ndt-server.go
This PR adds support for enabling TLS automatically via the [autocert](https://pkg.go.dev/golang.org/x/crypto/acme/autocert) package. In particular, the two new flags `-autocert.enabled` and `-autocert.hostname` enable this feature. On the first HTTPS request, ndt-server will automatically try to get a certificate from LetsEncrypt, assuming the requested hostname matches what's in the `-autocert.hostname` file.
The reason for it being a file is that the in the BYOS scenario the hostname is generated by the autojoin `register` client and written to a file.  
(FYI @nkinkade )
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/402)
=> Add support for automatic TLS encryption via autocert

README.md
The [NDT7 protocol](https://github.com/m-lab/ndt-server/blob/main/spec/ndt7-protocol.md) mentions M-Lab uses Linux 4.19. Certain key `TCP_INFO` struct members are only available in Linux 4.19+ (notably [`bytes_sent`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ba113c3aa79a7f941ac162d05a3620bdc985c58d)), so for consistency update the `README.md` to say the same.
btw, the NDT7 protocol also says:
> An implementation running on
> a kernel where a specific `TCP_INFO` variable mentioned in this specification
> is missing SHOULD NOT include such variable in the `TCPInfo` object sent to
> the client.
but that is not what this implementation does, it sends a full `TCPInfo` object where missing variables have `0` value.
- - -
This change is [<img …
=> Update README.md to Linux 4.19

TestDockerfile, ndt-server.go
Unconditionally disable HTTP/2 in ndt-server to fix WebSocket connection failures in Firefox.
- Windows 11 + Chrome (latest)
- Windows 11 + Firefox (latest) 
- Windows 11 + Edge (latest)
- macOS Sonoma + Chrome (latest)
- macOS Sonoma + Safari (latest)
- iPhone 14 + Safari 16
- iPhone 15 Pro + Safari 17
- Samsung Galaxy S24 + Chrome (Android 14)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/411)
=> fix: disable HTTP/2 to resolve WebSocket compatibility issues
