Dockerfile, README.md, ndt-server.go, ndt-server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/15)
=> Cleanups for golint, move base image to Alpine, add badges to README and a few helpful notes

.travis.yml, cmd/ndt-cloud-client/main.go, ndt-server.go, ndt-server_test.go, ndt7/client.go, ndt7/server.go, ndt7/spec.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/17)
=> Add prototype of next generation NDT protocol

.gitignore, ndt-server.go, netx/setsockopt.go, netx/setsockopt_linux.go
Based on join work with @stephen-soltesz. While there gitignore
the certificate files that are generated for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/20)
=> ndt-server: add support for TCP BBR

.gitignore, Dockerfile, bbr/bbr.go, build.sh, fdcache/fdcache.go, html/ndt7.html, ndt-server.go, ndt7/log.go, ndt7/metadata.go, ndt7/resultsfile.go, ndt7/server.go, ndt7/spec.go, spec/data-format.md, spec/ndt7-protocol.md, tcpinfox/tcpinfox.go, tcpinfox/tcpinfox_linux.go, tcpinfox/tcpinfox_stub.go, version/version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/36)
=> Include TCP_INFO and save results on disk

ndt-server.go, ndt/c2s/c2s.go, ndt/metrics/metrics.go, ndt/s2c/s2c.go, ndt/tcplistener/tcplistener.go, ndt/testresponder/testresponder.go, ndt/testrunner.go
I thought I would be adding tests, but I ended up refactoring even more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/42)
=> Refactors even further.  Compiles and runs.

fdcache/fdcache.go, legacy/c2s/c2s.go, legacy/metrics/metrics.go, legacy/s2c/s2c.go, legacy/testresponder/testresponder.go, logging/logging.go, ndt-server.go, ndt-server_test.go, ndt7/client.go, ndt7/model/appinfo.go, ndt7/model/bbrinfo.go, ndt7/model/measurement.go, ndt7/model/tcpinfo.go, ndt7/resultsfile.go, ndt7/server.go, ndt7/server/download/download.go, ndt7/server/results/file.go, ndt7/server/results/metadata.go, ndt7/spec.go, ndt7/spec/spec.go, tcpinfox/tcpinfox.go, tcpinfox/tcpinfox_linux.go, tcpinfox/tcpinfox_stub.go, version/version.go
I believe there are _more_ opportunities for refactoring. Here I'm starting to refactor the server to separate functionality across logical boundaries and increase code velocity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/45)
=> Refactor to increase code velocity

.travis.yml, ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-cloud/46)
=> The -coverpkg=all argument may fix our coverage weirdness.

ndt-server.go, ndt7/server/download/download.go, ndt7/server/listener/listener.go
Closes #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/59)
=> Make ndt7 work again

.travis.yml, Dockerfile, TestDockerfile, build.sh, fdcache/fdcache.go, ndt-server.go, ndt-server_test.go, ndt7/server/download/download.go, ndt7/server/results/file.go, ndt7/server/results/metadata.go, test.sh, testdata/package.json
Makes ndt7 save its data in a well-formed directory structure.
Also adds UUIDs to the filename and to the metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/60)
=> Adds UUID support to NDT7

legacy/c2s/c2s.go, legacy/protocol/protocol.go, legacy/protocol/protocol_test.go, legacy/s2c/s2c.go, legacy/testresponder/testresponder.go, legacy/web100/web100.go
Measure MinRTT because that metric is needed for OneBox.
Unblocks new platform work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/73)
=> Measure MinRTT.

Dockerfile, build.sh
Closes #79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/80)
=> Make sure we build a fully static binary

ndt7/server/results/file.go
Closes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/81)
=> ndt7/s/r/file.go: no colons in file names

legacy/s2c/s2c.go
Intended to fix #83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/84)
=> Add args to the goroutine to prevent null pointers.

fdcache/fdcache.go
Part of https://github.com/m-lab/uuid/issues/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/86)
=> Use the new uuid library

ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/88)
=> ndt-server.go: forward -datadir to ndt7

legacy/legacy.go
Part of https://github.com/m-lab/dev-tracker/issues/219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/91)
=> Add log to error message

build.sh, ndt-server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/94)
=> Package moved

Dockerfile, build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/96)
=> Adds a metric that encodes the commit hash of the code.

.travis.yml
See https://github.com/m-lab/ndt-server/pull/99#issuecomment-482182853.
Cherry picked from #99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/102)
=> travis: use xenial so we can set socket cookies

.travis.yml, AUTHORS, cmd/ndt-client/client/client.go, cmd/ndt-client/main.go, fdcache/fdcache.go, html/libndt7.js, html/ndt7-worker.js, html/ndt7.html, ndt-server.go, ndt7/handler/handler.go, ndt7/upload/upload.go
I think it's better to start merging an implementation of the upload, albeit imperfect, and then experiment with it while this implementation is in tree and deployed on some test servers.
Supersedes #62 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/99)
=> Initial implementation of ndt7 upload

legacy/c2s/c2s.go, legacy/s2c/s2c.go, legacy/testresponder/testresponder.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/108)
=> Unify timeouts.

legacy/plain/plain.go, legacy/singleserving/server.go, ndt-server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/111)
=> Support plain clients

ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/114)
=> Save data to ndt7 subdir

legacy/c2s/c2s.go, legacy/handler/wshandler.go, legacy/legacy.go, legacy/metrics/metrics.go, legacy/ndt/server.go, legacy/plain/plain.go, legacy/s2c/s2c.go, legacy/singleserving/server.go, legacy/tcplistener/tcplistener.go, metrics/metrics.go, ndt7/listener/listener.go
Call the correct code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/115)
=> Fix goroutine leak

TestDockerfile, ndt-server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/116)
=> Adds libndt as part of our integration tests

legacy/c2s/c2s.go, legacy/handler/wshandler.go, legacy/legacy.go, legacy/ndt/server.go, legacy/plain/plain.go, legacy/protocol/messager.go, legacy/protocol/messager_test.go, legacy/protocol/protocol.go, legacy/s2c/s2c.go, ndt-server.go, ndt-server_test.go
Adds a Messager type to encode messages.
Fixes a resolver-based test flake.
Fixes #65 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/118)
=> Adds a Messager type to encode messages.

ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/120)
=> Improve plain text message

legacy/legacy.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/135)
=> Add readable test suites and move PanicOnError after metric Observe

spec/ndt7-protocol.md
Closes #113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/127)
=> spec: set max message size at 1<<20

legacy/c2s/c2s.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/137)
=> Calculate rate based on actual test duration

metrics/metrics.go, ndt5/README.md, ndt5/c2s/c2s.go, ndt5/meta/meta.go, ndt5/meta/meta_test.go, ndt5/metrics/metrics.go, ndt5/ndt/server.go, ndt5/ndt5.go, ndt5/plain/plain.go, ndt5/s2c/s2c.go, ndt5/singleserving/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/169)
=> Improve error & panic metrics

html/ndt-browser-client.js
Continuation of https://github.com/m-lab/ndt-server/pull/170 
Code uses the same pattern as found in https://github.com/m-lab/ndt-server/blob/master/testdata/unittest_client.js#L250-L291
FYI: @ryanrolds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/172)
=> fix(ndt5/c2s): start upload when connection is ready

ndt5/protocol/messager.go, ndt5/protocol/protocol.go, ndt5/protocol/protocol_test.go, ndt5/s2c/s2c.go
Hopefully fixes one major source of errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/175)
=> Robust s2c receive

ndt-server_test.go, ndt5/c2s/c2s.go, ndt5/c2s/c2s_test.go, ndt5/protocol/protocol.go, ndt5/web100/web100_linux.go, ndt5/web100/web100_stub.go
Eliminates quantization of c2s upload results, adds unit tests, and eliminates several potential sources of goroutine leaks.
Part of https://github.com/m-lab/dev-tracker/issues/412
Fixes #144 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/179)
=> Smooth c2s

bbr/bbr_linux.go, cmd/ndt-client/client/client.go, ndt-server.go, ndt7/closer/closer.go, ndt7/download/sender/sender.go, ndt7/handler/handler.go, ndt7/measurer/measurer.go, ndt7/model/appinfo.go, ndt7/model/bbrinfo.go, ndt7/model/connectioninfo.go, ndt7/model/measurement.go, ndt7/model/tcpinfo.go, ndt7/receiver/receiver.go, ndt7/spec/spec.go, ndt7/upload/sender/sender.go
This PR contains a set of small, independent changes aimed at implementing v0.8.0 of the ndt7 spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/183)
=> ndt7: implement v0.8.0 of the spec

ndt7/measurer/measurer.go, spec/ndt7-protocol.md
While there also remove a typo from the spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/189)
=> ndt7/measurer: fix log message

ndt5/s2c/s2c.go
Fixes https://github.com/m-lab/ndt-server/issues/207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/208)
=> Use TCPInfo.BytesAcked to calculate s2c download rate

fullstack/Dockerfile, fullstack/start.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/214)
=> Adds packet-headers to the measurementlab/ndt image

ndt5/c2s/c2s.go, ndt5/ndt5.go, ndt5/s2c/s2c.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/219)
=> Adds UUIDs to error logs.

ndt7/measurer/measurer.go
Just a name change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/223)
=> MakeTicker -> NewTicker

ndt-server.go, ndt7/results/file.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/224)
=> ndt7: $datadir/ndt7/download => $datadir/ndt7download

fullstack/start.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/229)
=> Fix the way we are calling the fullstack components

html/ndt7-upload.js
Simpler means fewer places for bugs to hide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/250)
=> Make ndt7 upload client simpler

spec/ndt7-protocol.md
… upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/254)
=> ndt7-protocol.md: servers SHOULD send counterflow measurements during upload

README.md, ndt-server.go, ndt-server_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/222)
=> Make ndt7 work over cleartext

ndt7/results/file.go
This change fixes https://github.com/m-lab/ndt-server/issues/263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/264)
=> Remove ndt7 datatype directory decorations

ndt-server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/265)
=> Preserve chain with txcontroller, update flag name for consistency

logging/logging.go, logging/logging_test.go
Tiny code cleanup because I have quarantine brain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/284)
=> Coverage improvement in one package

ndt7/handler/handler.go
This change fixes a bug introduced by the refactor of https://github.com/m-lab/ndt-server/pull/292 that closed the conn shortly after creating it.
This change moves the close to the main `runMeasurement` which allows the measurement to complete.
NOTE: I was relying on the existing integration/unit tests to assess correct behavior. Evidently they were not resilient to this failure (and surprisingly, considering this broken both upload and download). More unit tests are needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/294)
=> Fix: close conn after returning from runMeasurement handler

fullstack/Dockerfile, fullstack/start.sh
Also improve error handling in start.sh
Fixes #287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/325)
=> Fix the fullstack build

ndt-server.go
This PR introduces a new `-canary` boolean command-line flag.
When this flag is set, a `-canary` suffix is automatically added to the `version.Version` variable, which ends up in saved measurements and will help us identify data from canary releases. E.g.
```json
{
"GitShortCommit": "84608e1",
"Version": "v0.20.6-4-g84608e1-canary",
"ServerIP": "127.0.0.1",
"ServerPort": 8080,
"ClientIP": "127.0.0.1",
"ClientPort": 43406,
"StartTime": "2021-06-28T10:19:05.622318959Z",
"EndTime": "2021-06-28T10:19:15.62552359Z",
"Download": {
[...]
```
(Also, some formatting changes made by gofmt on unrelated code.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/336)
=> Add -canary command-line flag

README.md
Add references to ndt7 client repositories within github.com/m-lab
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/347)
=> Add references to ndt7 clients

Dockerfile, Dockerfile.local, cmd/generate-schemas/go.mod, go.mod
Part of https://github.com/m-lab/dev-tracker/issues/771
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/394)
=> Update go version to 1.20

ndt7/handler/handler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-server/414)
=> fix: restore warnonerror.Close for ndt7 results
